/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSimuladosRouteImport } from './routes/_authenticated/simulados'
import { Route as AuthenticatedRevisoesRouteImport } from './routes/_authenticated/revisoes'
import { Route as AuthenticatedRepertoriosRouteImport } from './routes/_authenticated/repertorios'
import { Route as AuthenticatedRedacaoRouteImport } from './routes/_authenticated/redacao'
import { Route as AuthenticatedProgressoRouteImport } from './routes/_authenticated/progresso'
import { Route as AuthenticatedMateriasRouteImport } from './routes/_authenticated/materias'
import { Route as AuthenticatedGradeRouteImport } from './routes/_authenticated/grade'
import { Route as AuthenticatedCronogramaRouteImport } from './routes/_authenticated/cronograma'
import { Route as AuthenticatedCoragemRouteImport } from './routes/_authenticated/coragem'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedMateriasIndexRouteImport } from './routes/_authenticated/materias.index'
import { Route as AuthenticatedMateriasIdRouteImport } from './routes/_authenticated/materias.$id'
import { Route as ApiPublicCronPopularAgendasRouteImport } from './routes/api/public/cron/popular-agendas'
import { Route as AuthenticatedMateriasIdSequenciaRouteImport } from './routes/_authenticated/materias.$id.sequencia'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSimuladosRoute = AuthenticatedSimuladosRouteImport.update({
  id: '/simulados',
  path: '/simulados',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRevisoesRoute = AuthenticatedRevisoesRouteImport.update({
  id: '/revisoes',
  path: '/revisoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRepertoriosRoute =
  AuthenticatedRepertoriosRouteImport.update({
    id: '/repertorios',
    path: '/repertorios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRedacaoRoute = AuthenticatedRedacaoRouteImport.update({
  id: '/redacao',
  path: '/redacao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProgressoRoute = AuthenticatedProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMateriasRoute = AuthenticatedMateriasRouteImport.update({
  id: '/materias',
  path: '/materias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGradeRoute = AuthenticatedGradeRouteImport.update({
  id: '/grade',
  path: '/grade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCronogramaRoute = AuthenticatedCronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoragemRoute = AuthenticatedCoragemRouteImport.update({
  id: '/coragem',
  path: '/coragem',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMateriasIndexRoute =
  AuthenticatedMateriasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMateriasRoute,
  } as any)
const AuthenticatedMateriasIdRoute = AuthenticatedMateriasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMateriasRoute,
} as any)
const ApiPublicCronPopularAgendasRoute =
  ApiPublicCronPopularAgendasRouteImport.update({
    id: '/api/public/cron/popular-agendas',
    path: '/api/public/cron/popular-agendas',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMateriasIdSequenciaRoute =
  AuthenticatedMateriasIdSequenciaRouteImport.update({
    id: '/sequencia',
    path: '/sequencia',
    getParentRoute: () => AuthenticatedMateriasIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/coragem': typeof AuthenticatedCoragemRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/grade': typeof AuthenticatedGradeRoute
  '/materias': typeof AuthenticatedMateriasRouteWithChildren
  '/progresso': typeof AuthenticatedProgressoRoute
  '/redacao': typeof AuthenticatedRedacaoRoute
  '/repertorios': typeof AuthenticatedRepertoriosRoute
  '/revisoes': typeof AuthenticatedRevisoesRoute
  '/simulados': typeof AuthenticatedSimuladosRoute
  '/materias/$id': typeof AuthenticatedMateriasIdRouteWithChildren
  '/materias/': typeof AuthenticatedMateriasIndexRoute
  '/materias/$id/sequencia': typeof AuthenticatedMateriasIdSequenciaRoute
  '/api/public/cron/popular-agendas': typeof ApiPublicCronPopularAgendasRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/coragem': typeof AuthenticatedCoragemRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/grade': typeof AuthenticatedGradeRoute
  '/progresso': typeof AuthenticatedProgressoRoute
  '/redacao': typeof AuthenticatedRedacaoRoute
  '/repertorios': typeof AuthenticatedRepertoriosRoute
  '/revisoes': typeof AuthenticatedRevisoesRoute
  '/simulados': typeof AuthenticatedSimuladosRoute
  '/': typeof AuthenticatedIndexRoute
  '/materias/$id': typeof AuthenticatedMateriasIdRouteWithChildren
  '/materias': typeof AuthenticatedMateriasIndexRoute
  '/materias/$id/sequencia': typeof AuthenticatedMateriasIdSequenciaRoute
  '/api/public/cron/popular-agendas': typeof ApiPublicCronPopularAgendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/coragem': typeof AuthenticatedCoragemRoute
  '/_authenticated/cronograma': typeof AuthenticatedCronogramaRoute
  '/_authenticated/grade': typeof AuthenticatedGradeRoute
  '/_authenticated/materias': typeof AuthenticatedMateriasRouteWithChildren
  '/_authenticated/progresso': typeof AuthenticatedProgressoRoute
  '/_authenticated/redacao': typeof AuthenticatedRedacaoRoute
  '/_authenticated/repertorios': typeof AuthenticatedRepertoriosRoute
  '/_authenticated/revisoes': typeof AuthenticatedRevisoesRoute
  '/_authenticated/simulados': typeof AuthenticatedSimuladosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/materias/$id': typeof AuthenticatedMateriasIdRouteWithChildren
  '/_authenticated/materias/': typeof AuthenticatedMateriasIndexRoute
  '/_authenticated/materias/$id/sequencia': typeof AuthenticatedMateriasIdSequenciaRoute
  '/api/public/cron/popular-agendas': typeof ApiPublicCronPopularAgendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/coragem'
    | '/cronograma'
    | '/grade'
    | '/materias'
    | '/progresso'
    | '/redacao'
    | '/repertorios'
    | '/revisoes'
    | '/simulados'
    | '/materias/$id'
    | '/materias/'
    | '/materias/$id/sequencia'
    | '/api/public/cron/popular-agendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/configuracoes'
    | '/coragem'
    | '/cronograma'
    | '/grade'
    | '/progresso'
    | '/redacao'
    | '/repertorios'
    | '/revisoes'
    | '/simulados'
    | '/'
    | '/materias/$id'
    | '/materias'
    | '/materias/$id/sequencia'
    | '/api/public/cron/popular-agendas'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/configuracoes'
    | '/_authenticated/coragem'
    | '/_authenticated/cronograma'
    | '/_authenticated/grade'
    | '/_authenticated/materias'
    | '/_authenticated/progresso'
    | '/_authenticated/redacao'
    | '/_authenticated/repertorios'
    | '/_authenticated/revisoes'
    | '/_authenticated/simulados'
    | '/_authenticated/'
    | '/_authenticated/materias/$id'
    | '/_authenticated/materias/'
    | '/_authenticated/materias/$id/sequencia'
    | '/api/public/cron/popular-agendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicCronPopularAgendasRoute: typeof ApiPublicCronPopularAgendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simulados': {
      id: '/_authenticated/simulados'
      path: '/simulados'
      fullPath: '/simulados'
      preLoaderRoute: typeof AuthenticatedSimuladosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/revisoes': {
      id: '/_authenticated/revisoes'
      path: '/revisoes'
      fullPath: '/revisoes'
      preLoaderRoute: typeof AuthenticatedRevisoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repertorios': {
      id: '/_authenticated/repertorios'
      path: '/repertorios'
      fullPath: '/repertorios'
      preLoaderRoute: typeof AuthenticatedRepertoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/redacao': {
      id: '/_authenticated/redacao'
      path: '/redacao'
      fullPath: '/redacao'
      preLoaderRoute: typeof AuthenticatedRedacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/progresso': {
      id: '/_authenticated/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof AuthenticatedProgressoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/materias': {
      id: '/_authenticated/materias'
      path: '/materias'
      fullPath: '/materias'
      preLoaderRoute: typeof AuthenticatedMateriasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grade': {
      id: '/_authenticated/grade'
      path: '/grade'
      fullPath: '/grade'
      preLoaderRoute: typeof AuthenticatedGradeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cronograma': {
      id: '/_authenticated/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof AuthenticatedCronogramaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coragem': {
      id: '/_authenticated/coragem'
      path: '/coragem'
      fullPath: '/coragem'
      preLoaderRoute: typeof AuthenticatedCoragemRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/materias/': {
      id: '/_authenticated/materias/'
      path: '/'
      fullPath: '/materias/'
      preLoaderRoute: typeof AuthenticatedMateriasIndexRouteImport
      parentRoute: typeof AuthenticatedMateriasRoute
    }
    '/_authenticated/materias/$id': {
      id: '/_authenticated/materias/$id'
      path: '/$id'
      fullPath: '/materias/$id'
      preLoaderRoute: typeof AuthenticatedMateriasIdRouteImport
      parentRoute: typeof AuthenticatedMateriasRoute
    }
    '/api/public/cron/popular-agendas': {
      id: '/api/public/cron/popular-agendas'
      path: '/api/public/cron/popular-agendas'
      fullPath: '/api/public/cron/popular-agendas'
      preLoaderRoute: typeof ApiPublicCronPopularAgendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/materias/$id/sequencia': {
      id: '/_authenticated/materias/$id/sequencia'
      path: '/sequencia'
      fullPath: '/materias/$id/sequencia'
      preLoaderRoute: typeof AuthenticatedMateriasIdSequenciaRouteImport
      parentRoute: typeof AuthenticatedMateriasIdRoute
    }
  }
}

interface AuthenticatedMateriasIdRouteChildren {
  AuthenticatedMateriasIdSequenciaRoute: typeof AuthenticatedMateriasIdSequenciaRoute
}

const AuthenticatedMateriasIdRouteChildren: AuthenticatedMateriasIdRouteChildren =
  {
    AuthenticatedMateriasIdSequenciaRoute:
      AuthenticatedMateriasIdSequenciaRoute,
  }

const AuthenticatedMateriasIdRouteWithChildren =
  AuthenticatedMateriasIdRoute._addFileChildren(
    AuthenticatedMateriasIdRouteChildren,
  )

interface AuthenticatedMateriasRouteChildren {
  AuthenticatedMateriasIdRoute: typeof AuthenticatedMateriasIdRouteWithChildren
  AuthenticatedMateriasIndexRoute: typeof AuthenticatedMateriasIndexRoute
}

const AuthenticatedMateriasRouteChildren: AuthenticatedMateriasRouteChildren = {
  AuthenticatedMateriasIdRoute: AuthenticatedMateriasIdRouteWithChildren,
  AuthenticatedMateriasIndexRoute: AuthenticatedMateriasIndexRoute,
}

const AuthenticatedMateriasRouteWithChildren =
  AuthenticatedMateriasRoute._addFileChildren(
    AuthenticatedMateriasRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCoragemRoute: typeof AuthenticatedCoragemRoute
  AuthenticatedCronogramaRoute: typeof AuthenticatedCronogramaRoute
  AuthenticatedGradeRoute: typeof AuthenticatedGradeRoute
  AuthenticatedMateriasRoute: typeof AuthenticatedMateriasRouteWithChildren
  AuthenticatedProgressoRoute: typeof AuthenticatedProgressoRoute
  AuthenticatedRedacaoRoute: typeof AuthenticatedRedacaoRoute
  AuthenticatedRepertoriosRoute: typeof AuthenticatedRepertoriosRoute
  AuthenticatedRevisoesRoute: typeof AuthenticatedRevisoesRoute
  AuthenticatedSimuladosRoute: typeof AuthenticatedSimuladosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCoragemRoute: AuthenticatedCoragemRoute,
  AuthenticatedCronogramaRoute: AuthenticatedCronogramaRoute,
  AuthenticatedGradeRoute: AuthenticatedGradeRoute,
  AuthenticatedMateriasRoute: AuthenticatedMateriasRouteWithChildren,
  AuthenticatedProgressoRoute: AuthenticatedProgressoRoute,
  AuthenticatedRedacaoRoute: AuthenticatedRedacaoRoute,
  AuthenticatedRepertoriosRoute: AuthenticatedRepertoriosRoute,
  AuthenticatedRevisoesRoute: AuthenticatedRevisoesRoute,
  AuthenticatedSimuladosRoute: AuthenticatedSimuladosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicCronPopularAgendasRoute: ApiPublicCronPopularAgendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
